# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_list.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_add_list_window(object):
    def setupUi(self, add_list_window):
        add_list_window.setObjectName("add_list_window")
        add_list_window.resize(900, 800)
        add_list_window.setMinimumSize(QtCore.QSize(900, 800))
        add_list_window.setMaximumSize(QtCore.QSize(900, 800))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        add_list_window.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("PoLIZANE.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        add_list_window.setWindowIcon(icon)
        add_list_window.setStyleSheet("background-color: white;")
        self.add_list_screen = QtWidgets.QWidget(add_list_window)
        self.add_list_screen.setObjectName("add_list_screen")
        self.add_list_label = QtWidgets.QLabel(self.add_list_screen)
        self.add_list_label.setGeometry(QtCore.QRect(380, 10, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(26)
        self.add_list_label.setFont(font)
        self.add_list_label.setStyleSheet("color: rgb(49, 87, 44);")
        self.add_list_label.setObjectName("add_list_label")
        self.save_button = QtWidgets.QPushButton(self.add_list_screen)
        self.save_button.setGeometry(QtCore.QRect(40, 640, 250, 80))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        self.save_button.setFont(font)
        self.save_button.setStyleSheet("background-color: rgb(49, 87, 44);\n"
"color: white;\n"
"border-radius: 12px;")
        self.save_button.setObjectName("save_button")
        self.delete_button = QtWidgets.QPushButton(self.add_list_screen)
        self.delete_button.setGeometry(QtCore.QRect(610, 640, 250, 80))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        self.delete_button.setFont(font)
        self.delete_button.setStyleSheet("background-color: rgb(49, 87, 44);\n"
"color: white;\n"
"border-radius: 12px;")
        self.delete_button.setObjectName("delete_button")
        self.list_name = QtWidgets.QPlainTextEdit(self.add_list_screen)
        self.list_name.setGeometry(QtCore.QRect(40, 90, 820, 90))
        self.list_name.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.list_name.setStyleSheet("border-style: solid;\n"
"border-width: 2px;\n"
"border-radius: 12px;\n"
"border-color: rgb(49, 87, 44);\n"
"placeholder {\n"
"  color: rgb(49, 87, 44, 75);\n"
"};\n"
" font-size: 24px;")
        self.list_name.setObjectName("list_name")
        self.add_button = QtWidgets.QPushButton(self.add_list_screen)
        self.add_button.setGeometry(QtCore.QRect(300, 200, 300, 90))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        self.add_button.setFont(font)
        self.add_button.setStyleSheet("background-color: white;\n"
"color:  rgb(49, 87, 44);\n"
"border-radius: 12px;\n"
"border: solid;\n"
"border-color:  rgb(49, 87, 44);\n"
"border-width: 2px;")
        self.add_button.setObjectName("add_button")
        self.list_list = QtWidgets.QListWidget(self.add_list_screen)
        self.list_list.setGeometry(QtCore.QRect(40, 310, 820, 291))
        self.list_list.setStyleSheet("border-style: solid;\n"
"border-width: 2px;\n"
"border-radius: 12px;\n"
"border-color: rgb(49, 87, 44);\n"
"placeholder {\n"
"  color: rgb(49, 87, 44, 75);\n"
"};\n"
" font-size: 24px;")
        self.list_list.setObjectName("list_list")
        add_list_window.setCentralWidget(self.add_list_screen)
        self.statusbar = QtWidgets.QStatusBar(add_list_window)
        self.statusbar.setObjectName("statusbar")
        add_list_window.setStatusBar(self.statusbar)

        self.retranslateUi(add_list_window)
        QtCore.QMetaObject.connectSlotsByName(add_list_window)

    def retranslateUi(self, add_list_window):
        _translate = QtCore.QCoreApplication.translate
        add_list_window.setWindowTitle(_translate("add_list_window", "PoLIZANE"))
        self.add_list_label.setStatusTip(_translate("add_list_window", "Add list"))
        self.add_list_label.setText(_translate("add_list_window", "Add list"))
        self.save_button.setStatusTip(_translate("add_list_window", "Click save to add list to Shopping Lists"))
        self.save_button.setText(_translate("add_list_window", "Save"))
        self.delete_button.setStatusTip(_translate("add_list_window", "Click delete if you don\'t want to add this list to the Shopping Lists"))
        self.delete_button.setText(_translate("add_list_window", "Delete"))
        self.list_name.setStatusTip(_translate("add_list_window", "Type list name here"))
        self.list_name.setPlaceholderText(_translate("add_list_window", "List name"))
        self.add_button.setStatusTip(_translate("add_list_window", "Click plus to add new list"))
        self.add_button.setText(_translate("add_list_window", "+"))
        self.list_list.setStatusTip(_translate("add_list_window", "List of ingredients"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    add_list_window = QtWidgets.QMainWindow()
    ui = Ui_add_list_window()
    ui.setupUi(add_list_window)
    add_list_window.show()
    sys.exit(app.exec_())
