from database.database_controller import *

# database testing ===========================================================================================
test_ingredient = Ingredient(name="test ingredient", unit="g", amount=1)
test_ingredient2 = Ingredient(name="test ingredient2", unit="g", amount=2)
add(test_ingredient)
add(test_ingredient2)
print("\nIn the fridge ingredients 1 and 2:")
print(*get_ingredients_in_fridge(), sep="   \n  ")
test_ingredient.amount = 30
update(test_ingredient)
print("\nTest ingredient after the update")
print(*get_ingredients_in_fridge(), sep="   \n  ")
test_recipe = Recipe(name="test recipe", licks=1, image="uri to image")
test_ingredient3 = Ingredient(name="test ingredient3", unit="g", amount=2, recipe=test_recipe)
test_ingredient4 = Ingredient(name="test ingredient4", unit="g", amount=2, recipe=test_recipe)
test_step = Step(recipe=test_recipe, number=1, description="some text")
test_timer = Timer(recipe=test_recipe, name="test timer", time_val=60)
add(test_recipe)
add(test_ingredient3)
add(test_ingredient4)
add(test_step)
add(test_timer)
print("\nRecipe of the ingredient3:" + str(get_recipe_of_the_ingredient(test_ingredient3)))
print("\nRecipe of the step" + str(get_recipe_of_the_step(test_step)))
print("\nRecipe of the timer" + str(get_recipe_of_the_timer(test_timer)))
print("\nIngredients in the recipe:")
print(*get_ingredients_with_recipe_obj(test_recipe), sep="  \n  ")
print("\nSteps in the recipe:")
print(*get_steps_with_recipe_obj(test_recipe), sep="  \n  ")
print("\nTimers in the recipe:")
print(*get_timers_with_recipe_obj(test_recipe), sep="  \n  ")
test_recipe.name = "name after update"
update(test_recipe)
print("\nRecipe after update:" + str(get_recipe_of_the_ingredient(test_ingredient3)))
temp_rec_id = test_recipe.id
# delete(test_recipe)
# print("Ingredients after recipe deletion:")
# print(*get_ingredients_with_recipe_id(temp_rec_id), sep="   \n  ")
print("\nRecipe of the ingredient3 after deletion:" + str(get_recipe_of_the_ingredient(test_ingredient3)))
delete(test_ingredient)
delete(test_ingredient2)
print("\nAfter deleting the fridge:")
print(*get_ingredients_in_fridge(), sep="   \n  ")
# database testing ===========================================================================================
