# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addIngredient.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddIngredientWindow(object):
    def setupUi(self, AddIngredientWindow):
        AddIngredientWindow.setObjectName("AddIngredientWindow")
        AddIngredientWindow.resize(900, 650)
        AddIngredientWindow.setMinimumSize(QtCore.QSize(900, 650))
        AddIngredientWindow.setMaximumSize(QtCore.QSize(900, 650))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        AddIngredientWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("325314459_826693388428270_2168916561632903173_n.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AddIngredientWindow.setWindowIcon(icon)
        AddIngredientWindow.setStyleSheet("background-color: white;")
        self.addIngredientScreen = QtWidgets.QWidget(AddIngredientWindow)
        self.addIngredientScreen.setObjectName("addIngredientScreen")
        self.saveButton = QtWidgets.QPushButton(self.addIngredientScreen)
        self.saveButton.setGeometry(QtCore.QRect(100, 490, 250, 80))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        self.saveButton.setFont(font)
        self.saveButton.setAccessibleDescription("")
        self.saveButton.setStyleSheet("background-color: rgb(49, 87, 44);\n"
"color: white;\n"
"border-radius: 12px;")
        self.saveButton.setObjectName("saveButton")
        self.deleteButton = QtWidgets.QPushButton(self.addIngredientScreen)
        self.deleteButton.setGeometry(QtCore.QRect(550, 490, 250, 80))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        self.deleteButton.setFont(font)
        self.deleteButton.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.deleteButton.setStyleSheet("background-color: rgb(49, 87, 44);\n"
"color: white;\n"
"border-radius: 12px;")
        self.deleteButton.setObjectName("deleteButton")
        self.title = QtWidgets.QLabel(self.addIngredientScreen)
        self.title.setGeometry(QtCore.QRect(0, 0, 900, 140))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(26)
        self.title.setFont(font)
        self.title.setStyleSheet("color: rgb(49, 87, 44)")
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.ingredientNameTextArea = QtWidgets.QPlainTextEdit(self.addIngredientScreen)
        self.ingredientNameTextArea.setGeometry(QtCore.QRect(100, 140, 700, 90))
        self.ingredientNameTextArea.setStyleSheet("border-style: solid;\n"
"border-width: 2px;\n"
"border-radius: 12px;\n"
"border-color: rgb(49, 87, 44);\n"
"font-size: 24px;\n"
"")
        self.ingredientNameTextArea.setObjectName("ingredientNameTextArea")
        self.amount = QtWidgets.QPlainTextEdit(self.addIngredientScreen)
        self.amount.setGeometry(QtCore.QRect(100, 240, 340, 90))
        self.amount.setStyleSheet("border-style: solid;\n"
"border-width: 2px;\n"
"border-radius: 12px;\n"
"border-color: rgb(49, 87, 44);\n"
"font-size: 24px;")
        self.amount.setObjectName("amount")
        self.unitTextArea = QtWidgets.QPlainTextEdit(self.addIngredientScreen)
        self.unitTextArea.setGeometry(QtCore.QRect(460, 240, 340, 90))
        self.unitTextArea.setAccessibleDescription("")
        self.unitTextArea.setStyleSheet("border-style: solid;\n"
"border-width: 2px;\n"
"border-radius: 12px;\n"
"border-color: rgb(49, 87, 44);\n"
"font-size: 24px;")
        self.unitTextArea.setObjectName("unitTextArea")
        AddIngredientWindow.setCentralWidget(self.addIngredientScreen)
        self.statusbar = QtWidgets.QStatusBar(AddIngredientWindow)
        self.statusbar.setObjectName("statusbar")
        AddIngredientWindow.setStatusBar(self.statusbar)

        self.retranslateUi(AddIngredientWindow)
        QtCore.QMetaObject.connectSlotsByName(AddIngredientWindow)

    def retranslateUi(self, AddIngredientWindow):
        _translate = QtCore.QCoreApplication.translate
        AddIngredientWindow.setWindowTitle(_translate("AddIngredientWindow", "PoLIZANE"))
        self.saveButton.setStatusTip(_translate("AddIngredientWindow", "Save your ingredient"))
        self.saveButton.setText(_translate("AddIngredientWindow", "Save"))
        self.deleteButton.setStatusTip(_translate("AddIngredientWindow", "Delete your ingredient"))
        self.deleteButton.setText(_translate("AddIngredientWindow", "Delete"))
        self.title.setText(_translate("AddIngredientWindow", "Add ingredient"))
        self.ingredientNameTextArea.setStatusTip(_translate("AddIngredientWindow", "Enter name of your ingredient"))
        self.ingredientNameTextArea.setPlaceholderText(_translate("AddIngredientWindow", "Ingredient name"))
        self.amount.setStatusTip(_translate("AddIngredientWindow", "Enter amount of your ingredient"))
        self.amount.setPlaceholderText(_translate("AddIngredientWindow", "Amount"))
        self.unitTextArea.setStatusTip(_translate("AddIngredientWindow", "Enter unit of your ingredient"))
        self.unitTextArea.setPlaceholderText(_translate("AddIngredientWindow", "Unit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddIngredientWindow = QtWidgets.QMainWindow()
    ui = Ui_AddIngredientWindow()
    ui.setupUi(AddIngredientWindow)
    AddIngredientWindow.show()
    sys.exit(app.exec_())
