# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addTimer.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddTimerWindow(object):
    def setupUi(self, AddTimerWindow):
        AddTimerWindow.setObjectName("AddTimerWindow")
        AddTimerWindow.resize(900, 650)
        AddTimerWindow.setMinimumSize(QtCore.QSize(900, 650))
        AddTimerWindow.setMaximumSize(QtCore.QSize(900, 650))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("325314459_826693388428270_2168916561632903173_n.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AddTimerWindow.setWindowIcon(icon)
        AddTimerWindow.setStyleSheet("background-color: white;")
        self.addTimerScreen = QtWidgets.QWidget(AddTimerWindow)
        self.addTimerScreen.setObjectName("addTimerScreen")
        self.title = QtWidgets.QLabel(self.addTimerScreen)
        self.title.setGeometry(QtCore.QRect(0, 0, 900, 140))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(26)
        self.title.setFont(font)
        self.title.setStyleSheet("color: rgb(49, 87, 44)")
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.saveButton = QtWidgets.QPushButton(self.addTimerScreen)
        self.saveButton.setGeometry(QtCore.QRect(100, 490, 250, 80))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        self.saveButton.setFont(font)
        self.saveButton.setAccessibleDescription("")
        self.saveButton.setStyleSheet("background-color: rgb(49, 87, 44);\n"
"color: white;\n"
"border-radius: 12px;")
        self.saveButton.setObjectName("saveButton")
        self.deleteButton = QtWidgets.QPushButton(self.addTimerScreen)
        self.deleteButton.setGeometry(QtCore.QRect(550, 490, 250, 80))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        self.deleteButton.setFont(font)
        self.deleteButton.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.deleteButton.setStyleSheet("background-color: rgb(49, 87, 44);\n"
"color: white;\n"
"border-radius: 12px;")
        self.deleteButton.setObjectName("deleteButton")
        self.hoursTextArea = QtWidgets.QPlainTextEdit(self.addTimerScreen)
        self.hoursTextArea.setGeometry(QtCore.QRect(100, 260, 200, 90))
        self.hoursTextArea.setStyleSheet("border-style: solid;\n"
"border-width: 2px;\n"
"border-radius: 12px;\n"
"border-color: rgb(49, 87, 44);\n"
"font-size: 24px;")
        self.hoursTextArea.setObjectName("hoursTextArea")
        self.timerNameTextArea = QtWidgets.QPlainTextEdit(self.addTimerScreen)
        self.timerNameTextArea.setGeometry(QtCore.QRect(100, 140, 700, 90))
        self.timerNameTextArea.setStyleSheet("border-style: solid;\n"
"border-width: 2px;\n"
"border-radius: 12px;\n"
"border-color: rgb(49, 87, 44);\n"
"font-size: 24px;\n"
"")
        self.timerNameTextArea.setObjectName("timerNameTextArea")
        self.MinutesTextArea = QtWidgets.QPlainTextEdit(self.addTimerScreen)
        self.MinutesTextArea.setGeometry(QtCore.QRect(350, 260, 200, 90))
        self.MinutesTextArea.setStyleSheet("border-style: solid;\n"
"border-width: 2px;\n"
"border-radius: 12px;\n"
"border-color: rgb(49, 87, 44);\n"
"font-size: 24px;")
        self.MinutesTextArea.setObjectName("MinutesTextArea")
        self.SecondsTextArea = QtWidgets.QPlainTextEdit(self.addTimerScreen)
        self.SecondsTextArea.setGeometry(QtCore.QRect(600, 260, 200, 90))
        self.SecondsTextArea.setStyleSheet("border-style: solid;\n"
"border-width: 2px;\n"
"border-radius: 12px;\n"
"border-color: rgb(49, 87, 44);\n"
"font-size: 24px;")
        self.SecondsTextArea.setObjectName("SecondsTextArea")
        self.colon1 = QtWidgets.QLabel(self.addTimerScreen)
        self.colon1.setGeometry(QtCore.QRect(300, 230, 40, 140))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(26)
        self.colon1.setFont(font)
        self.colon1.setStyleSheet("color: rgb(49, 87, 44)")
        self.colon1.setAlignment(QtCore.Qt.AlignCenter)
        self.colon1.setObjectName("colon1")
        self.colon2 = QtWidgets.QLabel(self.addTimerScreen)
        self.colon2.setGeometry(QtCore.QRect(550, 230, 40, 140))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(26)
        self.colon2.setFont(font)
        self.colon2.setStyleSheet("color: rgb(49, 87, 44)")
        self.colon2.setAlignment(QtCore.Qt.AlignCenter)
        self.colon2.setObjectName("colon2")
        AddTimerWindow.setCentralWidget(self.addTimerScreen)
        self.statusbar = QtWidgets.QStatusBar(AddTimerWindow)
        self.statusbar.setObjectName("statusbar")
        AddTimerWindow.setStatusBar(self.statusbar)

        self.retranslateUi(AddTimerWindow)
        QtCore.QMetaObject.connectSlotsByName(AddTimerWindow)

    def retranslateUi(self, AddTimerWindow):
        _translate = QtCore.QCoreApplication.translate
        AddTimerWindow.setWindowTitle(_translate("AddTimerWindow", "PoLIZANE"))
        self.title.setText(_translate("AddTimerWindow", "Add Timer"))
        self.saveButton.setStatusTip(_translate("AddTimerWindow", "Save your timer"))
        self.saveButton.setText(_translate("AddTimerWindow", "Save"))
        self.deleteButton.setStatusTip(_translate("AddTimerWindow", "Delete your timer"))
        self.deleteButton.setText(_translate("AddTimerWindow", "Delete"))
        self.hoursTextArea.setStatusTip(_translate("AddTimerWindow", "Enter amount of hours"))
        self.hoursTextArea.setPlaceholderText(_translate("AddTimerWindow", "Hours"))
        self.timerNameTextArea.setStatusTip(_translate("AddTimerWindow", "Enter name of your timer"))
        self.timerNameTextArea.setPlaceholderText(_translate("AddTimerWindow", "Timer name"))
        self.MinutesTextArea.setStatusTip(_translate("AddTimerWindow", "Enter amount of minutes"))
        self.MinutesTextArea.setPlaceholderText(_translate("AddTimerWindow", "Minutes"))
        self.SecondsTextArea.setStatusTip(_translate("AddTimerWindow", "Enter amount of seconds"))
        self.SecondsTextArea.setPlaceholderText(_translate("AddTimerWindow", "Seconds"))
        self.colon1.setText(_translate("AddTimerWindow", ":"))
        self.colon2.setText(_translate("AddTimerWindow", ":"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddTimerWindow = QtWidgets.QMainWindow()
    ui = Ui_AddTimerWindow()
    ui.setupUi(AddTimerWindow)
    AddTimerWindow.show()
    sys.exit(app.exec_())
