# Form implementation generated from reading ui file 'c:\Users\weraj\OneDrive\Pulpit\ACS\SEM_V\Software Engineering\PoLIZANE\UI\add_step.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_add_step_window(object):
    def setupUi(self, add_step_window):
        add_step_window.setObjectName("add_step_window")
        add_step_window.resize(900, 650)
        add_step_window.setMinimumSize(QtCore.QSize(900, 650))
        add_step_window.setMaximumSize(QtCore.QSize(900, 650))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\weraj\\OneDrive\\Pulpit\\ACS\\SEM_V\\Software Engineering\\PoLIZANE\\UI\\PoLIZANE.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        add_step_window.setWindowIcon(icon)
        add_step_window.setStyleSheet("background-color: white;")
        self.add_step_screen = QtWidgets.QWidget(add_step_window)
        self.add_step_screen.setObjectName("add_step_screen")
        self.save_button = QtWidgets.QPushButton(self.add_step_screen)
        self.save_button.setGeometry(QtCore.QRect(40, 490, 250, 80))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        self.save_button.setFont(font)
        self.save_button.setStyleSheet("background-color: rgb(49, 87, 44);\n"
"color: white;\n"
"border-radius: 12px;")
        self.save_button.setObjectName("save_button")
        self.delete_button = QtWidgets.QPushButton(self.add_step_screen)
        self.delete_button.setGeometry(QtCore.QRect(610, 490, 250, 80))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        self.delete_button.setFont(font)
        self.delete_button.setStyleSheet("background-color: rgb(49, 87, 44);\n"
"color: white;\n"
"border-radius: 12px;")
        self.delete_button.setObjectName("delete_button")
        self.add_step_label = QtWidgets.QLabel(self.add_step_screen)
        self.add_step_label.setGeometry(QtCore.QRect(350, 10, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(26)
        self.add_step_label.setFont(font)
        self.add_step_label.setStyleSheet("color: rgb(49, 87, 44);")
        self.add_step_label.setObjectName("add_step_label")
        self.step_description_areatext = QtWidgets.QPlainTextEdit(self.add_step_screen)
        self.step_description_areatext.setGeometry(QtCore.QRect(40, 90, 820, 350))
        self.step_description_areatext.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.step_description_areatext.setStyleSheet("border-style: solid;\n"
"border-width: 2px;\n"
"border-radius: 12px;\n"
"border-color: rgb(49, 87, 44);\n"
"placeholder {\n"
"  color: rgb(49, 87, 44, 75);\n"
"};\n"
" font-size: 24px;")
        self.step_description_areatext.setObjectName("step_description_areatext")
        add_step_window.setCentralWidget(self.add_step_screen)
        self.statusbar = QtWidgets.QStatusBar(add_step_window)
        self.statusbar.setObjectName("statusbar")
        add_step_window.setStatusBar(self.statusbar)

        self.retranslateUi(add_step_window)
        QtCore.QMetaObject.connectSlotsByName(add_step_window)

    def retranslateUi(self, add_step_window):
        _translate = QtCore.QCoreApplication.translate
        add_step_window.setWindowTitle(_translate("add_step_window", "PoLIZANE"))
        self.save_button.setStatusTip(_translate("add_step_window", "Click save to add step to the Recipe"))
        self.save_button.setText(_translate("add_step_window", "Save"))
        self.delete_button.setStatusTip(_translate("add_step_window", "Click delete if you don\'t want to add this step to the recipe"))
        self.delete_button.setText(_translate("add_step_window", "Delete"))
        self.add_step_label.setStatusTip(_translate("add_step_window", "Add step"))
        self.add_step_label.setText(_translate("add_step_window", "Add step"))
        self.step_description_areatext.setStatusTip(_translate("add_step_window", "Type description of the step here"))
        self.step_description_areatext.setPlaceholderText(_translate("add_step_window", "Step description"))
