# Form implementation generated from reading ui file 'c:\Users\weraj\OneDrive\Pulpit\ACS\SEM_V\Software Engineering\PoLIZANE\UI\lists_screen.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_lists_window(object):
    def setupUi(self, lists_window):
        lists_window.setObjectName("lists_window")
        lists_window.resize(1200, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(lists_window.sizePolicy().hasHeightForWidth())
        lists_window.setSizePolicy(sizePolicy)
        lists_window.setMinimumSize(QtCore.QSize(1200, 800))
        lists_window.setMaximumSize(QtCore.QSize(1200, 800))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\weraj\\OneDrive\\Pulpit\\ACS\\SEM_V\\Software Engineering\\PoLIZANE\\UI\\../logo/polizane.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        lists_window.setWindowIcon(icon)
        lists_window.setStatusTip("")
        lists_window.setStyleSheet("background-color: rgb(49, 87, 44);\n"
"color: rgb(255, 255, 255);")
        lists_window.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.recpie_screen = QtWidgets.QWidget(lists_window)
        self.recpie_screen.setObjectName("recpie_screen")
        self.add_button = QtWidgets.QPushButton(self.recpie_screen)
        self.add_button.setGeometry(QtCore.QRect(30, 20, 1150, 80))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        self.add_button.setFont(font)
        self.add_button.setStyleSheet("background-color: rgb(49, 87, 44);\n"
"color: white;\n"
"border-radius: 12px;\n"
"border-width: 2px;\n"
"border-color: white;\n"
"border-style: outset;")
        self.add_button.setObjectName("add_button")
        self.display = QtWidgets.QListWidget(self.recpie_screen)
        self.display.setGeometry(QtCore.QRect(30, 130, 1150, 571))
        self.display.setStyleSheet("border-color: rgb(49, 87, 44);\n"
"border-width: 0px;\n"
"border-style: outset;")
        self.display.setObjectName("display")
        lists_window.setCentralWidget(self.recpie_screen)
        self.statusbar = QtWidgets.QStatusBar(lists_window)
        self.statusbar.setObjectName("statusbar")
        lists_window.setStatusBar(self.statusbar)

        self.retranslateUi(lists_window)
        QtCore.QMetaObject.connectSlotsByName(lists_window)

    def retranslateUi(self, lists_window):
        _translate = QtCore.QCoreApplication.translate
        lists_window.setWindowTitle(_translate("lists_window", "PoLIZANE - LISTS"))
        self.add_button.setStatusTip(_translate("lists_window", "Click this button to add a new list to the database"))
        self.add_button.setText(_translate("lists_window", "+"))
