# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'viewList.ui'
#
# Created by: PyQt5 ui_designs code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


# noinspection PyPep8Naming,PyAttributeOutsideInit,PyShadowingNames
class Ui_ViewListWindow(object):
    def setupUi(self, ViewListWindow):
        ViewListWindow.setObjectName("ViewListWindow")
        ViewListWindow.resize(900, 650)
        ViewListWindow.setMinimumSize(QtCore.QSize(900, 650))
        ViewListWindow.setMaximumSize(QtCore.QSize(900, 650))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("325314459_826693388428270_2168916561632903173_n.png"), QtGui.QIcon.Normal,
                       QtGui.QIcon.Off)
        ViewListWindow.setWindowIcon(icon)
        ViewListWindow.setStyleSheet("background-color:white;\n"
                                     "")
        self.viewListScreen = QtWidgets.QWidget(ViewListWindow)
        self.viewListScreen.setObjectName("viewListScreen")
        self.title = QtWidgets.QLabel(self.viewListScreen)
        self.title.setGeometry(QtCore.QRect(0, 0, 900, 140))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(26)
        self.title.setFont(font)
        self.title.setStyleSheet("color: rgb(49, 87, 44)")
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.editButton = QtWidgets.QPushButton(self.viewListScreen)
        self.editButton.setGeometry(QtCore.QRect(190, 540, 250, 80))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        self.editButton.setFont(font)
        self.editButton.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.editButton.setStyleSheet("background-color: rgb(49, 87, 44);\n"
                                      "color: white;\n"
                                      "border-radius: 12px;")
        self.editButton.setObjectName("editButton")
        self.listOfIngredients = QtWidgets.QListWidget(self.viewListScreen)
        self.listOfIngredients.setGeometry(QtCore.QRect(60, 120, 780, 390))
        self.listOfIngredients.setStyleSheet("border-color: rgb(49, 87, 44);\n"
                                             "border-width: 2px;\n"
                                             "border-style: solid;\n"
                                             "border-radius:12px;\n"
                                             "")
        self.listOfIngredients.setObjectName("listOfIngredients")
        self.deleteButton = QtWidgets.QPushButton(self.viewListScreen)
        self.deleteButton.setGeometry(QtCore.QRect(460, 540, 250, 80))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        self.deleteButton.setFont(font)
        self.deleteButton.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.deleteButton.setStyleSheet("background-color: rgb(49, 87, 44);\n"
                                        "color: white;\n"
                                        "border-radius: 12px;")
        self.deleteButton.setObjectName("deleteButton")
        ViewListWindow.setCentralWidget(self.viewListScreen)
        self.statusbar = QtWidgets.QStatusBar(ViewListWindow)
        self.statusbar.setObjectName("statusbar")
        ViewListWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ViewListWindow)
        QtCore.QMetaObject.connectSlotsByName(ViewListWindow)

    def retranslateUi(self, ViewListWindow):
        _translate = QtCore.QCoreApplication.translate
        ViewListWindow.setWindowTitle(_translate("ViewListWindow", "PoLIZANE"))
        self.title.setText(_translate("ViewListWindow", "List name"))
        self.editButton.setStatusTip(_translate("ViewListWindow", "Edit your list"))
        self.editButton.setText(_translate("ViewListWindow", "Edit"))
        self.deleteButton.setStatusTip(_translate("ViewListWindow", "Delete your list"))
        self.deleteButton.setText(_translate("ViewListWindow", "Delete"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    ViewListWindow = QtWidgets.QMainWindow()
    ui = Ui_ViewListWindow()
    ui.setupUi(ViewListWindow)
    ViewListWindow.show()
    sys.exit(app.exec_())
